// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class CursoOfertado
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cursoOfertadoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.CursoOfertado";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Inicio("Inicio"),
		Fin("Fin"),
		Descripcion("Descripcion"),
		CursoOfertado_Docente("MyFirstModule.CursoOfertado_Docente"),
		CursoOfertado_Periodo("MyFirstModule.CursoOfertado_Periodo"),
		CursoOfertado_Curso("MyFirstModule.CursoOfertado_Curso");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CursoOfertado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CursoOfertado(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cursoOfertadoMendixObject)
	{
		if (cursoOfertadoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cursoOfertadoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cursoOfertadoMendixObject = cursoOfertadoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CursoOfertado.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.CursoOfertado initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.CursoOfertado.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.CursoOfertado initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CursoOfertado(context, mendixObject);
	}

	public static myfirstmodule.proxies.CursoOfertado load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CursoOfertado.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CursoOfertado> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.CursoOfertado.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Inicio
	 */
	public final java.util.Date getInicio()
	{
		return getInicio(getContext());
	}

	/**
	 * @param context
	 * @return value of Inicio
	 */
	public final java.util.Date getInicio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Inicio.toString());
	}

	/**
	 * Set value of Inicio
	 * @param inicio
	 */
	public final void setInicio(java.util.Date inicio)
	{
		setInicio(getContext(), inicio);
	}

	/**
	 * Set value of Inicio
	 * @param context
	 * @param inicio
	 */
	public final void setInicio(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date inicio)
	{
		getMendixObject().setValue(context, MemberNames.Inicio.toString(), inicio);
	}

	/**
	 * @return value of Fin
	 */
	public final java.util.Date getFin()
	{
		return getFin(getContext());
	}

	/**
	 * @param context
	 * @return value of Fin
	 */
	public final java.util.Date getFin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Fin.toString());
	}

	/**
	 * Set value of Fin
	 * @param fin
	 */
	public final void setFin(java.util.Date fin)
	{
		setFin(getContext(), fin);
	}

	/**
	 * Set value of Fin
	 * @param context
	 * @param fin
	 */
	public final void setFin(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date fin)
	{
		getMendixObject().setValue(context, MemberNames.Fin.toString(), fin);
	}

	/**
	 * @return value of Descripcion
	 */
	public final java.lang.String getDescripcion()
	{
		return getDescripcion(getContext());
	}

	/**
	 * @param context
	 * @return value of Descripcion
	 */
	public final java.lang.String getDescripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Descripcion.toString());
	}

	/**
	 * Set value of Descripcion
	 * @param descripcion
	 */
	public final void setDescripcion(java.lang.String descripcion)
	{
		setDescripcion(getContext(), descripcion);
	}

	/**
	 * Set value of Descripcion
	 * @param context
	 * @param descripcion
	 */
	public final void setDescripcion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descripcion)
	{
		getMendixObject().setValue(context, MemberNames.Descripcion.toString(), descripcion);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CursoOfertado_Docente
	 */
	public final myfirstmodule.proxies.Docente getCursoOfertado_Docente() throws com.mendix.core.CoreException
	{
		return getCursoOfertado_Docente(getContext());
	}

	/**
	 * @param context
	 * @return value of CursoOfertado_Docente
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Docente getCursoOfertado_Docente(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Docente result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CursoOfertado_Docente.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Docente.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CursoOfertado_Docente
	 * @param cursoofertado_docente
	 */
	public final void setCursoOfertado_Docente(myfirstmodule.proxies.Docente cursoofertado_docente)
	{
		setCursoOfertado_Docente(getContext(), cursoofertado_docente);
	}

	/**
	 * Set value of CursoOfertado_Docente
	 * @param context
	 * @param cursoofertado_docente
	 */
	public final void setCursoOfertado_Docente(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Docente cursoofertado_docente)
	{
		if (cursoofertado_docente == null) {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Docente.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Docente.toString(), cursoofertado_docente.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CursoOfertado_Periodo
	 */
	public final myfirstmodule.proxies.Periodo getCursoOfertado_Periodo() throws com.mendix.core.CoreException
	{
		return getCursoOfertado_Periodo(getContext());
	}

	/**
	 * @param context
	 * @return value of CursoOfertado_Periodo
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Periodo getCursoOfertado_Periodo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Periodo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CursoOfertado_Periodo.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Periodo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CursoOfertado_Periodo
	 * @param cursoofertado_periodo
	 */
	public final void setCursoOfertado_Periodo(myfirstmodule.proxies.Periodo cursoofertado_periodo)
	{
		setCursoOfertado_Periodo(getContext(), cursoofertado_periodo);
	}

	/**
	 * Set value of CursoOfertado_Periodo
	 * @param context
	 * @param cursoofertado_periodo
	 */
	public final void setCursoOfertado_Periodo(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Periodo cursoofertado_periodo)
	{
		if (cursoofertado_periodo == null) {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Periodo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Periodo.toString(), cursoofertado_periodo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CursoOfertado_Curso
	 */
	public final myfirstmodule.proxies.Curso getCursoOfertado_Curso() throws com.mendix.core.CoreException
	{
		return getCursoOfertado_Curso(getContext());
	}

	/**
	 * @param context
	 * @return value of CursoOfertado_Curso
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Curso getCursoOfertado_Curso(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Curso result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CursoOfertado_Curso.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Curso.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CursoOfertado_Curso
	 * @param cursoofertado_curso
	 */
	public final void setCursoOfertado_Curso(myfirstmodule.proxies.Curso cursoofertado_curso)
	{
		setCursoOfertado_Curso(getContext(), cursoofertado_curso);
	}

	/**
	 * Set value of CursoOfertado_Curso
	 * @param context
	 * @param cursoofertado_curso
	 */
	public final void setCursoOfertado_Curso(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Curso cursoofertado_curso)
	{
		if (cursoofertado_curso == null) {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Curso.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CursoOfertado_Curso.toString(), cursoofertado_curso.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cursoOfertadoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CursoOfertado that = (myfirstmodule.proxies.CursoOfertado) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
