// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Docente
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject docenteMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Docente";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Identificacion("Identificacion"),
		Nombre("Nombre"),
		Titulo("Titulo"),
		Estado("Estado");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Docente(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Docente(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject docenteMendixObject)
	{
		if (docenteMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, docenteMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.docenteMendixObject = docenteMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Docente.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Docente initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Docente.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Docente initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Docente(context, mendixObject);
	}

	public static myfirstmodule.proxies.Docente load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Docente.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Docente> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Docente.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Identificacion
	 */
	public final java.lang.String getIdentificacion()
	{
		return getIdentificacion(getContext());
	}

	/**
	 * @param context
	 * @return value of Identificacion
	 */
	public final java.lang.String getIdentificacion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Identificacion.toString());
	}

	/**
	 * Set value of Identificacion
	 * @param identificacion
	 */
	public final void setIdentificacion(java.lang.String identificacion)
	{
		setIdentificacion(getContext(), identificacion);
	}

	/**
	 * Set value of Identificacion
	 * @param context
	 * @param identificacion
	 */
	public final void setIdentificacion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identificacion)
	{
		getMendixObject().setValue(context, MemberNames.Identificacion.toString(), identificacion);
	}

	/**
	 * @return value of Nombre
	 */
	public final java.lang.String getNombre()
	{
		return getNombre(getContext());
	}

	/**
	 * @param context
	 * @return value of Nombre
	 */
	public final java.lang.String getNombre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nombre.toString());
	}

	/**
	 * Set value of Nombre
	 * @param nombre
	 */
	public final void setNombre(java.lang.String nombre)
	{
		setNombre(getContext(), nombre);
	}

	/**
	 * Set value of Nombre
	 * @param context
	 * @param nombre
	 */
	public final void setNombre(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nombre)
	{
		getMendixObject().setValue(context, MemberNames.Nombre.toString(), nombre);
	}

	/**
	 * @return value of Titulo
	 */
	public final java.lang.String getTitulo()
	{
		return getTitulo(getContext());
	}

	/**
	 * @param context
	 * @return value of Titulo
	 */
	public final java.lang.String getTitulo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Titulo.toString());
	}

	/**
	 * Set value of Titulo
	 * @param titulo
	 */
	public final void setTitulo(java.lang.String titulo)
	{
		setTitulo(getContext(), titulo);
	}

	/**
	 * Set value of Titulo
	 * @param context
	 * @param titulo
	 */
	public final void setTitulo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titulo)
	{
		getMendixObject().setValue(context, MemberNames.Titulo.toString(), titulo);
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final myfirstmodule.proxies.EstadoDocente getEstado()
	{
		return getEstado(getContext());
	}

	/**
	 * @param context
	 * @return value of Estado
	 */
	public final myfirstmodule.proxies.EstadoDocente getEstado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Estado.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.EstadoDocente.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final void setEstado(myfirstmodule.proxies.EstadoDocente estado)
	{
		setEstado(getContext(), estado);
	}

	/**
	 * Set value of Estado
	 * @param context
	 * @param estado
	 */
	public final void setEstado(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EstadoDocente estado)
	{
		if (estado != null) {
			getMendixObject().setValue(context, MemberNames.Estado.toString(), estado.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Estado.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return docenteMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Docente that = (myfirstmodule.proxies.Docente) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
