// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Estudiante
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject estudianteMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Estudiante";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Cedula("Cedula"),
		RazonSocial("RazonSocial"),
		Edad("Edad");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Estudiante(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Estudiante(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject estudianteMendixObject)
	{
		if (estudianteMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, estudianteMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.estudianteMendixObject = estudianteMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Estudiante.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Estudiante initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Estudiante.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Estudiante initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Estudiante(context, mendixObject);
	}

	public static myfirstmodule.proxies.Estudiante load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Estudiante.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Estudiante> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Estudiante.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Cedula
	 */
	public final java.lang.String getCedula()
	{
		return getCedula(getContext());
	}

	/**
	 * @param context
	 * @return value of Cedula
	 */
	public final java.lang.String getCedula(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cedula.toString());
	}

	/**
	 * Set value of Cedula
	 * @param cedula
	 */
	public final void setCedula(java.lang.String cedula)
	{
		setCedula(getContext(), cedula);
	}

	/**
	 * Set value of Cedula
	 * @param context
	 * @param cedula
	 */
	public final void setCedula(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cedula)
	{
		getMendixObject().setValue(context, MemberNames.Cedula.toString(), cedula);
	}

	/**
	 * @return value of RazonSocial
	 */
	public final java.lang.String getRazonSocial()
	{
		return getRazonSocial(getContext());
	}

	/**
	 * @param context
	 * @return value of RazonSocial
	 */
	public final java.lang.String getRazonSocial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RazonSocial.toString());
	}

	/**
	 * Set value of RazonSocial
	 * @param razonsocial
	 */
	public final void setRazonSocial(java.lang.String razonsocial)
	{
		setRazonSocial(getContext(), razonsocial);
	}

	/**
	 * Set value of RazonSocial
	 * @param context
	 * @param razonsocial
	 */
	public final void setRazonSocial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String razonsocial)
	{
		getMendixObject().setValue(context, MemberNames.RazonSocial.toString(), razonsocial);
	}

	/**
	 * @return value of Edad
	 */
	public final java.lang.Integer getEdad()
	{
		return getEdad(getContext());
	}

	/**
	 * @param context
	 * @return value of Edad
	 */
	public final java.lang.Integer getEdad(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Edad.toString());
	}

	/**
	 * Set value of Edad
	 * @param edad
	 */
	public final void setEdad(java.lang.Integer edad)
	{
		setEdad(getContext(), edad);
	}

	/**
	 * Set value of Edad
	 * @param context
	 * @param edad
	 */
	public final void setEdad(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer edad)
	{
		getMendixObject().setValue(context, MemberNames.Edad.toString(), edad);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return estudianteMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Estudiante that = (myfirstmodule.proxies.Estudiante) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
