// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Inscripcion
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject inscripcionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Inscripcion";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Observaciones("Observaciones"),
		Inscripcion_Estudiante("MyFirstModule.Inscripcion_Estudiante"),
		Inscripcion_CursoOfertado("MyFirstModule.Inscripcion_CursoOfertado");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Inscripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Inscripcion(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject inscripcionMendixObject)
	{
		if (inscripcionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, inscripcionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.inscripcionMendixObject = inscripcionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Inscripcion.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Inscripcion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Inscripcion.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Inscripcion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Inscripcion(context, mendixObject);
	}

	public static myfirstmodule.proxies.Inscripcion load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Inscripcion.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Inscripcion> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Inscripcion.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Observaciones
	 */
	public final java.lang.String getObservaciones()
	{
		return getObservaciones(getContext());
	}

	/**
	 * @param context
	 * @return value of Observaciones
	 */
	public final java.lang.String getObservaciones(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Observaciones.toString());
	}

	/**
	 * Set value of Observaciones
	 * @param observaciones
	 */
	public final void setObservaciones(java.lang.String observaciones)
	{
		setObservaciones(getContext(), observaciones);
	}

	/**
	 * Set value of Observaciones
	 * @param context
	 * @param observaciones
	 */
	public final void setObservaciones(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String observaciones)
	{
		getMendixObject().setValue(context, MemberNames.Observaciones.toString(), observaciones);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Inscripcion_Estudiante
	 */
	public final myfirstmodule.proxies.Estudiante getInscripcion_Estudiante() throws com.mendix.core.CoreException
	{
		return getInscripcion_Estudiante(getContext());
	}

	/**
	 * @param context
	 * @return value of Inscripcion_Estudiante
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Estudiante getInscripcion_Estudiante(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Estudiante result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Inscripcion_Estudiante.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Estudiante.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Inscripcion_Estudiante
	 * @param inscripcion_estudiante
	 */
	public final void setInscripcion_Estudiante(myfirstmodule.proxies.Estudiante inscripcion_estudiante)
	{
		setInscripcion_Estudiante(getContext(), inscripcion_estudiante);
	}

	/**
	 * Set value of Inscripcion_Estudiante
	 * @param context
	 * @param inscripcion_estudiante
	 */
	public final void setInscripcion_Estudiante(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Estudiante inscripcion_estudiante)
	{
		if (inscripcion_estudiante == null) {
			getMendixObject().setValue(context, MemberNames.Inscripcion_Estudiante.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Inscripcion_Estudiante.toString(), inscripcion_estudiante.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Inscripcion_CursoOfertado
	 */
	public final java.util.List<myfirstmodule.proxies.CursoOfertado> getInscripcion_CursoOfertado() throws com.mendix.core.CoreException
	{
		return getInscripcion_CursoOfertado(getContext());
	}

	/**
	 * @param context
	 * @return value of Inscripcion_CursoOfertado
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.CursoOfertado> getInscripcion_CursoOfertado(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.CursoOfertado> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Inscripcion_CursoOfertado.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.CursoOfertado.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Inscripcion_CursoOfertado
	 * @param inscripcion_cursoofertado
	 */
	public final void setInscripcion_CursoOfertado(java.util.List<myfirstmodule.proxies.CursoOfertado> inscripcion_cursoofertado)
	{
		setInscripcion_CursoOfertado(getContext(), inscripcion_cursoofertado);
	}

	/**
	 * Set value of Inscripcion_CursoOfertado
	 * @param context
	 * @param inscripcion_cursoofertado
	 */
	public final void setInscripcion_CursoOfertado(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.CursoOfertado> inscripcion_cursoofertado)
	{
		var identifiers = inscripcion_cursoofertado
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Inscripcion_CursoOfertado.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return inscripcionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Inscripcion that = (myfirstmodule.proxies.Inscripcion) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
