// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Periodo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject periodoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Periodo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Desde("Desde"),
		Hasta("Hasta"),
		Descripcion("Descripcion"),
		Estado("Estado");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Periodo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Periodo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject periodoMendixObject)
	{
		if (periodoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, periodoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.periodoMendixObject = periodoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Periodo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Periodo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Periodo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Periodo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Periodo(context, mendixObject);
	}

	public static myfirstmodule.proxies.Periodo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Periodo.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Periodo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Periodo.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Desde
	 */
	public final java.util.Date getDesde()
	{
		return getDesde(getContext());
	}

	/**
	 * @param context
	 * @return value of Desde
	 */
	public final java.util.Date getDesde(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Desde.toString());
	}

	/**
	 * Set value of Desde
	 * @param desde
	 */
	public final void setDesde(java.util.Date desde)
	{
		setDesde(getContext(), desde);
	}

	/**
	 * Set value of Desde
	 * @param context
	 * @param desde
	 */
	public final void setDesde(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date desde)
	{
		getMendixObject().setValue(context, MemberNames.Desde.toString(), desde);
	}

	/**
	 * @return value of Hasta
	 */
	public final java.util.Date getHasta()
	{
		return getHasta(getContext());
	}

	/**
	 * @param context
	 * @return value of Hasta
	 */
	public final java.util.Date getHasta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Hasta.toString());
	}

	/**
	 * Set value of Hasta
	 * @param hasta
	 */
	public final void setHasta(java.util.Date hasta)
	{
		setHasta(getContext(), hasta);
	}

	/**
	 * Set value of Hasta
	 * @param context
	 * @param hasta
	 */
	public final void setHasta(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date hasta)
	{
		getMendixObject().setValue(context, MemberNames.Hasta.toString(), hasta);
	}

	/**
	 * @return value of Descripcion
	 */
	public final java.lang.String getDescripcion()
	{
		return getDescripcion(getContext());
	}

	/**
	 * @param context
	 * @return value of Descripcion
	 */
	public final java.lang.String getDescripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Descripcion.toString());
	}

	/**
	 * Set value of Descripcion
	 * @param descripcion
	 */
	public final void setDescripcion(java.lang.String descripcion)
	{
		setDescripcion(getContext(), descripcion);
	}

	/**
	 * Set value of Descripcion
	 * @param context
	 * @param descripcion
	 */
	public final void setDescripcion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descripcion)
	{
		getMendixObject().setValue(context, MemberNames.Descripcion.toString(), descripcion);
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final myfirstmodule.proxies.EstadoPeriodo getEstado()
	{
		return getEstado(getContext());
	}

	/**
	 * @param context
	 * @return value of Estado
	 */
	public final myfirstmodule.proxies.EstadoPeriodo getEstado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Estado.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.EstadoPeriodo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final void setEstado(myfirstmodule.proxies.EstadoPeriodo estado)
	{
		setEstado(getContext(), estado);
	}

	/**
	 * Set value of Estado
	 * @param context
	 * @param estado
	 */
	public final void setEstado(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EstadoPeriodo estado)
	{
		if (estado != null) {
			getMendixObject().setValue(context, MemberNames.Estado.toString(), estado.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Estado.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return periodoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Periodo that = (myfirstmodule.proxies.Periodo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
